export interface Airport {
  name: string;
  city: string;
  country: string;
  iata: string;
}

export const AIRPORTS: Airport[] = [
  { name: "Changi Airport", city: "Singapore", country: "Singapore", iata: "SIN" },
  { name: "Dubai International Airport", city: "Dubai", country: "United Arab Emirates", iata: "DXB" },
  { name: "London Heathrow Airport", city: "London", country: "United Kingdom", iata: "LHR" },
  { name: "Hong Kong International Airport", city: "Hong Kong", country: "Hong Kong", iata: "HKG" },
  { name: "John F. Kennedy International Airport", city: "New York", country: "United States", iata: "JFK" },
  { name: "Charles de Gaulle Airport", city: "Paris", country: "France", iata: "CDG" },
  { name: "Amsterdam Airport Schiphol", city: "Amsterdam", country: "Netherlands", iata: "AMS" },
  { name: "Frankfurt Airport", city: "Frankfurt", country: "Germany", iata: "FRA" },
  { name: "Incheon International Airport", city: "Seoul", country: "South Korea", iata: "ICN" },
  { name: "Haneda Airport", city: "Tokyo", country: "Japan", iata: "HND" },
  { name: "Narita International Airport", city: "Tokyo", country: "Japan", iata: "NRT" },
  { name: "Shanghai Pudong International Airport", city: "Shanghai", country: "China", iata: "PVG" },
  { name: "Guangzhou Baiyun International Airport", city: "Guangzhou", country: "China", iata: "CAN" },
  { name: "Indira Gandhi International Airport", city: "Delhi", country: "India", iata: "DEL" },
  { name: "Chhatrapati Shivaji Maharaj International Airport", city: "Mumbai", country: "India", iata: "BOM" },
  { name: "Suvarnabhumi Airport", city: "Bangkok", country: "Thailand", iata: "BKK" },
  { name: "Kuala Lumpur International Airport", city: "Kuala Lumpur", country: "Malaysia", iata: "KUL" },
  { name: "Los Angeles International Airport", city: "Los Angeles", country: "United States", iata: "LAX" },
  { name: "San Francisco International Airport", city: "San Francisco", country: "United States", iata: "SFO" },
  { name: "O'Hare International Airport", city: "Chicago", country: "United States", iata: "ORD" },
  { name: "Dallas/Fort Worth International Airport", city: "Dallas", country: "United States", iata: "DFW" },
  { name: "Hartsfield-Jackson Atlanta International Airport", city: "Atlanta", country: "United States", iata: "ATL" },
  { name: "Toronto Pearson International Airport", city: "Toronto", country: "Canada", iata: "YYZ" },
  { name: "Vancouver International Airport", city: "Vancouver", country: "Canada", iata: "YVR" },
  { name: "Sydney Airport", city: "Sydney", country: "Australia", iata: "SYD" },
  { name: "Melbourne Airport", city: "Melbourne", country: "Australia", iata: "MEL" },
  { name: "Auckland Airport", city: "Auckland", country: "New Zealand", iata: "AKL" },
  { name: "Istanbul Airport", city: "Istanbul", country: "Turkey", iata: "IST" },
  { name: "Hamad International Airport", city: "Doha", country: "Qatar", iata: "DOH" },
  { name: "King Abdulaziz International Airport", city: "Jeddah", country: "Saudi Arabia", iata: "JED" },
  { name: "King Khalid International Airport", city: "Riyadh", country: "Saudi Arabia", iata: "RUH" },
  { name: "Zurich Airport", city: "Zurich", country: "Switzerland", iata: "ZRH" },
  { name: "Vienna International Airport", city: "Vienna", country: "Austria", iata: "VIE" },
  { name: "Brussels Airport", city: "Brussels", country: "Belgium", iata: "BRU" },
  { name: "Adolfo Suárez Madrid-Barajas Airport", city: "Madrid", country: "Spain", iata: "MAD" },
  { name: "Barcelona-El Prat Airport", city: "Barcelona", country: "Spain", iata: "BCN" },
  { name: "Leonardo da Vinci-Fiumicino Airport", city: "Rome", country: "Italy", iata: "FCO" },
  { name: "Malpensa Airport", city: "Milan", country: "Italy", iata: "MXP" },
  { name: "Munich Airport", city: "Munich", country: "Germany", iata: "MUC" },
  { name: "Copenhagen Airport", city: "Copenhagen", country: "Denmark", iata: "CPH" },
  { name: "Stockholm Arlanda Airport", city: "Stockholm", country: "Sweden", iata: "ARN" },
  { name: "Oslo Airport, Gardermoen", city: "Oslo", country: "Norway", iata: "OSL" },
  { name: "Helsinki Airport", city: "Helsinki", country: "Finland", iata: "HEL" },
  { name: "Dublin Airport", city: "Dublin", country: "Ireland", iata: "DUB" },
  { name: "Lisbon Airport", city: "Lisbon", country: "Portugal", iata: "LIS" },
  { name: "Ben Gurion Airport", city: "Tel Aviv", country: "Israel", iata: "TLV" },
  { name: "Cairo International Airport", city: "Cairo", country: "Egypt", iata: "CAI" },
  { name: "OR Tambo International Airport", city: "Johannesburg", country: "South Africa", iata: "JNB" },
  { name: "Cape Town International Airport", city: "Cape Town", country: "South Africa", iata: "CPT" },
  { name: "Bole International Airport", city: "Addis Ababa", country: "Ethiopia", iata: "ADD" },
  { name: "Jomo Kenyatta International Airport", city: "Nairobi", country: "Kenya", iata: "NBO" },
  { name: "Casablanca Mohammed V International Airport", city: "Casablanca", country: "Morocco", iata: "CMN" },
  { name: "São Paulo/Guarulhos International Airport", city: "São Paulo", country: "Brazil", iata: "GRU" },
  { name: "Rio de Janeiro/Galeão International Airport", city: "Rio de Janeiro", country: "Brazil", iata: "GIG" },
  { name: "Ministro Pistarini International Airport", city: "Buenos Aires", country: "Argentina", iata: "EZE" },
  { name: "Arturo Merino Benítez International Airport", city: "Santiago", country: "Chile", iata: "SCL" },
  { name: "Jorge Chávez International Airport", city: "Lima", country: "Peru", iata: "LIM" },
  { name: "El Dorado International Airport", city: "Bogotá", country: "Colombia", iata: "BOG" },
  { name: "Mexico City International Airport", city: "Mexico City", country: "Mexico", iata: "MEX" },
  { name: "Cancún International Airport", city: "Cancún", country: "Mexico", iata: "CUN" },
  { name: "Kempegowda International Airport", city: "Bengaluru", country: "India", iata: "BLR" },
  { name: "Chennai International Airport", city: "Chennai", country: "India", iata: "MAA" },
  { name: "Netaji Subhash Chandra Bose International Airport", city: "Kolkata", country: "India", iata: "CCU" },
  { name: "Hyderabad International Airport", city: "Hyderabad", country: "India", iata: "HYD" },
  { name: "Tan Son Nhat International Airport", city: "Ho Chi Minh City", country: "Vietnam", iata: "SGN" },
  { name: "Noi Bai International Airport", city: "Hanoi", country: "Vietnam", iata: "HAN" },
  { name: "Ninoy Aquino International Airport", city: "Manila", country: "Philippines", iata: "MNL" },
  { name: "Soekarno-Hatta International Airport", city: "Jakarta", country: "Indonesia", iata: "CGK" },
  { name: "Ngurah Rai International Airport", city: "Bali", country: "Indonesia", iata: "DPS" },
  { name: "Don Mueang International Airport", city: "Bangkok", country: "Thailand", iata: "DMK" },
  { name: "Phuket International Airport", city: "Phuket", country: "Thailand", iata: "HKT" },
  { name: "Taiwan Taoyuan International Airport", city: "Taipei", country: "Taiwan", iata: "TPE" },
  { name: "Beijing Capital International Airport", city: "Beijing", country: "China", iata: "PEK" },
  { name: "Beijing Daxing International Airport", city: "Beijing", country: "China", iata: "PKX" },
  { name: "Chengdu Shuangliu International Airport", city: "Chengdu", country: "China", iata: "CTU" },
  { name: "Shenzhen Bao'an International Airport", city: "Shenzhen", country: "China", iata: "SZX" },
  { name: "Kunming Changshui International Airport", city: "Kunming", country: "China", iata: "KMG" },
  { name: "Xian Xianyang International Airport", city: "Xian", country: "China", iata: "XIY" },
  { name: "Hangzhou Xiaoshan International Airport", city: "Hangzhou", country: "China", iata: "HGH" },
  { name: "Chongqing Jiangbei International Airport", city: "Chongqing", country: "China", iata: "CKG" },
  { name: "Gatwick Airport", city: "London", country: "United Kingdom", iata: "LGW" },
  { name: "Manchester Airport", city: "Manchester", country: "United Kingdom", iata: "MAN" },
  { name: "Birmingham Airport", city: "Birmingham", country: "United Kingdom", iata: "BHX" },
  { name: "Edinburgh Airport", city: "Edinburgh", country: "United Kingdom", iata: "EDI" },
  { name: "Glasgow Airport", city: "Glasgow", country: "United Kingdom", iata: "GLA" },
  { name: "Nice Côte d'Azur Airport", city: "Nice", country: "France", iata: "NCE" },
  { name: "Lyon-Saint Exupéry Airport", city: "Lyon", country: "France", iata: "LYS" },
  { name: "Marseille Provence Airport", city: "Marseille", country: "France", iata: "MRS" },
  { name: "Toulouse-Blagnac Airport", city: "Toulouse", country: "France", iata: "TLS" },
  { name: "Geneva Airport", city: "Geneva", country: "Switzerland", iata: "GVA" },
  { name: "Berlin Brandenburg Airport", city: "Berlin", country: "Germany", iata: "BER" },
  { name: "Düsseldorf Airport", city: "Düsseldorf", country: "Germany", iata: "DUS" },
  { name: "Hamburg Airport", city: "Hamburg", country: "Germany", iata: "HAM" },
  { name: "Cologne Bonn Airport", city: "Cologne", country: "Germany", iata: "CGN" },
  { name: "Athens International Airport", city: "Athens", country: "Greece", iata: "ATH" },
  { name: "Prague Airport", city: "Prague", country: "Czech Republic", iata: "PRG" },
  { name: "Warsaw Chopin Airport", city: "Warsaw", country: "Poland", iata: "WAW" },
  { name: "Budapest Ferenc Liszt International Airport", city: "Budapest", country: "Hungary", iata: "BUD" },
  { name: "Sheremetyevo International Airport", city: "Moscow", country: "Russia", iata: "SVO" },
  { name: "Domodedovo International Airport", city: "Moscow", country: "Russia", iata: "DME" },
  { name: "Vnukovo International Airport", city: "Moscow", country: "Russia", iata: "VKO" },
  { name: "Pulkovo Airport", city: "Saint Petersburg", country: "Russia", iata: "LED" },
  { name: "Newark Liberty International Airport", city: "Newark", country: "United States", iata: "EWR" },
  { name: "LaGuardia Airport", city: "New York", country: "United States", iata: "LGA" },
  { name: "Logan International Airport", city: "Boston", country: "United States", iata: "BOS" },
  { name: "Philadelphia International Airport", city: "Philadelphia", country: "United States", iata: "PHL" },
  { name: "Washington Dulles International Airport", city: "Washington, D.C.", country: "United States", iata: "IAD" },
  { name: "Ronald Reagan Washington National Airport", city: "Washington, D.C.", country: "United States", iata: "DCA" },
  { name: "Miami International Airport", city: "Miami", country: "United States", iata: "MIA" },
  { name: "Orlando International Airport", city: "Orlando", country: "United States", iata: "MCO" },
  { name: "Tampa International Airport", city: "Tampa", country: "United States", iata: "TPA" },
  { name: "Fort Lauderdale-Hollywood International Airport", city: "Fort Lauderdale", country: "United States", iata: "FLL" },
  { name: "Charlotte Douglas International Airport", city: "Charlotte", country: "United States", iata: "CLT" },
  { name: "George Bush Intercontinental Airport", city: "Houston", country: "United States", iata: "IAH" },
  { name: "William P. Hobby Airport", city: "Houston", country: "United States", iata: "HOU" },
  { name: "Austin-Bergstrom International Airport", city: "Austin", country: "United States", iata: "AUS" },
  { name: "Phoenix Sky Harbor International Airport", city: "Phoenix", country: "United States", iata: "PHX" },
  { name: "McCarran International Airport", city: "Las Vegas", country: "United States", iata: "LAS" },
  { name: "Seattle-Tacoma International Airport", city: "Seattle", country: "United States", iata: "SEA" },
  { name: "Portland International Airport", city: "Portland", country: "United States", iata: "PDX" },
  { name: "Salt Lake City International Airport", city: "Salt Lake City", country: "United States", iata: "SLC" },
  { name: "Denver International Airport", city: "Denver", country: "United States", iata: "DEN" },
  { name: "Minneapolis-Saint Paul International Airport", city: "Minneapolis", country: "United States", iata: "MSP" },
  { name: "Detroit Metropolitan Airport", city: "Detroit", country: "United States", iata: "DTW" },
  { name: "Montreal-Pierre Elliott Trudeau International Airport", city: "Montreal", country: "Canada", iata: "YUL" },
  { name: "Calgary International Airport", city: "Calgary", country: "Canada", iata: "YYC" },
  { name: "Perth Airport", city: "Perth", country: "Australia", iata: "PER" },
  { name: "Brisbane Airport", city: "Brisbane", country: "Australia", iata: "BNE" },
  { name: "Adelaide Airport", city: "Adelaide", country: "Australia", iata: "ADL" },
  { name: "Melbourne Tullamarine Airport", city: "Melbourne", country: "Australia", iata: "MEL" },
  { name: "Christchurch Airport", city: "Christchurch", country: "New Zealand", iata: "CHC" },
  { name: "Wellington Airport", city: "Wellington", country: "New Zealand", iata: "WLG" },
  { name: "Nadi International Airport", city: "Nadi", country: "Fiji", iata: "NAN" },
  { name: "Abu Dhabi International Airport", city: "Abu Dhabi", country: "United Arab Emirates", iata: "AUH" },
  { name: "Sharjah International Airport", city: "Sharjah", country: "United Arab Emirates", iata: "SHJ" },
  { name: "Muscat International Airport", city: "Muscat", country: "Oman", iata: "MCT" },
  { name: "Bahrain International Airport", city: "Manama", country: "Bahrain", iata: "BAH" },
  { name: "Kuwait International Airport", city: "Kuwait City", country: "Kuwait", iata: "KWI" },
  { name: "Tehran Imam Khomeini International Airport", city: "Tehran", country: "Iran", iata: "IKA" },
  { name: "Beirut-Rafic Hariri International Airport", city: "Beirut", country: "Lebanon", iata: "BEY" },
  { name: "Amman Queen Alia International Airport", city: "Amman", country: "Jordan", iata: "AMM" },
  { name: "Colombo Bandaranaike International Airport", city: "Colombo", country: "Sri Lanka", iata: "CMB" },
  { name: "Dhaka Shahjalal International Airport", city: "Dhaka", country: "Bangladesh", iata: "DAC" },
  { name: "Karachi Jinnah International Airport", city: "Karachi", country: "Pakistan", iata: "KHI" },
  { name: "Lahore Allama Iqbal International Airport", city: "Lahore", country: "Pakistan", iata: "LHE" },
  { name: "Islamabad International Airport", city: "Islamabad", country: "Pakistan", iata: "ISB" },
  { name: "Male Velana International Airport", city: "Male", country: "Maldives", iata: "MLE" },
  { name: "Kathmandu Tribhuvan International Airport", city: "Kathmandu", country: "Nepal", iata: "KTM" },
  { name: "Tashkent International Airport", city: "Tashkent", country: "Uzbekistan", iata: "TAS" },
  { name: "Almaty International Airport", city: "Almaty", country: "Kazakhstan", iata: "ALA" },
  { name: "Nursultan Nazarbayev International Airport", city: "Astana", country: "Kazakhstan", iata: "NQZ" },
  { name: "Kyiv Boryspil International Airport", city: "Kyiv", country: "Ukraine", iata: "KBP" },
  { name: "Odesa International Airport", city: "Odesa", country: "Ukraine", iata: "ODS" },
  { name: "Bucharest Henri Coandă International Airport", city: "Bucharest", country: "Romania", iata: "OTP" },
  { name: "Sofia Airport", city: "Sofia", country: "Bulgaria", iata: "SOF" },
  { name: "Belgrade Nikola Tesla Airport", city: "Belgrade", country: "Serbia", iata: "BEG" },
  { name: "Zagreb Airport", city: "Zagreb", country: "Croatia", iata: "ZAG" },
  { name: "Ljubljana Jože Pučnik Airport", city: "Ljubljana", country: "Slovenia", iata: "LJU" },
  { name: "Venice Marco Polo Airport", city: "Venice", country: "Italy", iata: "VCE" },
  { name: "Naples International Airport", city: "Naples", country: "Italy", iata: "NAP" },
  { name: "Palermo Airport", city: "Palermo", country: "Italy", iata: "PMO" },
  { name: "Catania-Fontanarossa Airport", city: "Catania", country: "Italy", iata: "CTA" },
  { name: "Florence Airport", city: "Florence", country: "Italy", iata: "FLR" },
  { name: "Pisa International Airport", city: "Pisa", country: "Italy", iata: "PSA" },
  { name: "Bologna Guglielmo Marconi Airport", city: "Bologna", country: "Italy", iata: "BLQ" },
  { name: "Turin Airport", city: "Turin", country: "Italy", iata: "TRN" },
  { name: "Genoa Cristoforo Colombo Airport", city: "Genoa", country: "Italy", iata: "GOA" },
  { name: "Stuttgart Airport", city: "Stuttgart", country: "Germany", iata: "STR" },
  { name: "Hannover Airport", city: "Hannover", country: "Germany", iata: "HAJ" },
  { name: "Nuremberg Airport", city: "Nuremberg", country: "Germany", iata: "NUE" },
  { name: "Leipzig/Halle Airport", city: "Leipzig", country: "Germany", iata: "LEJ" },
  { name: "Bremen Airport", city: "Bremen", country: "Germany", iata: "BRE" },
  { name: "Luxembourg Airport", city: "Luxembourg City", country: "Luxembourg", iata: "LUX" },
  { name: "Basel-Mulhouse-Freiburg Airport", city: "Basel", country: "Switzerland", iata: "BSL" },
  { name: "Salzburg Airport", city: "Salzburg", country: "Austria", iata: "SZG" },
  { name: "Innsbruck Airport", city: "Innsbruck", country: "Austria", iata: "INN" },
  { name: "Graz Airport", city: "Graz", country: "Austria", iata: "GRZ" },
  { name: "Linz Airport", city: "Linz", country: "Austria", iata: "LNZ" },
  { name: "Antwerp International Airport", city: "Antwerp", country: "Belgium", iata: "ANR" },
  { name: "Ostend-Bruges International Airport", city: "Ostend", country: "Belgium", iata: "OST" },
  { name: "Liege Airport", city: "Liege", country: "Belgium", iata: "LGG" },
  { name: "Charleroi Airport", city: "Brussels", country: "Belgium", iata: "CRL" },
  { name: "Eindhoven Airport", city: "Eindhoven", country: "Netherlands", iata: "EIN" },
  { name: "Rotterdam The Hague Airport", city: "Rotterdam", country: "Netherlands", iata: "RTM" },
  { name: "Maastricht Aachen Airport", city: "Maastricht", country: "Netherlands", iata: "MST" },
  { name: "Groningen Airport Eelde", city: "Groningen", country: "Netherlands", iata: "GRQ" },
  { name: "Billund Airport", city: "Billund", country: "Denmark", iata: "BLL" },
  { name: "Aarhus Airport", city: "Aarhus", country: "Denmark", iata: "AAR" },
  { name: "Gothenburg Landvetter Airport", city: "Gothenburg", country: "Sweden", iata: "GOT" },
  { name: "Malmö Airport", city: "Malmö", country: "Sweden", iata: "MMX" },
  { name: "Stockholm Skavsta Airport", city: "Stockholm", country: "Sweden", iata: "NYO" },
  { name: "Stockholm Bromma Airport", city: "Stockholm", country: "Sweden", iata: "BMA" },
  { name: "Stavanger Airport, Sola", city: "Stavanger", country: "Norway", iata: "SVG" },
  { name: "Bergen Airport, Flesland", city: "Bergen", country: "Norway", iata: "BGO" },
  { name: "Trondheim Airport, Værnes", city: "Trondheim", country: "Norway", iata: "TRD" },
  { name: "Keflavík International Airport", city: "Reykjavík", country: "Iceland", iata: "KEF" },
  { name: "Reykjavík Airport", city: "Reykjavík", country: "Iceland", iata: "RKV" },
  { name: "Faroe Islands Airport", city: "Vágar", country: "Faroe Islands", iata: "FAE" },
  { name: "Tórshavn Airport", city: "Tórshavn", country: "Faroe Islands", iata: "THV" },
  { name: "Tallinn Airport", city: "Tallinn", country: "Estonia", iata: "TLL" },
  { name: "Riga International Airport", city: "Riga", country: "Latvia", iata: "RIX" },
  { name: "Vilnius Airport", city: "Vilnius", country: "Lithuania", iata: "VNO" },
  { name: "Kaunas Airport", city: "Kaunas", country: "Lithuania", iata: "KUN" },
  { name: "Larnaca International Airport", city: "Larnaca", country: "Cyprus", iata: "LCA" },
  { name: "Paphos International Airport", city: "Paphos", country: "Cyprus", iata: "PFO" },
  { name: "Malta International Airport", city: "Valletta", country: "Malta", iata: "MLA" },
  { name: "Gibraltar International Airport", city: "Gibraltar", country: "Gibraltar", iata: "GIB" },
  { name: "Tirana International Airport Nënë Tereza", city: "Tirana", country: "Albania", iata: "TIA" },
  { name: "Skopje International Airport", city: "Skopje", country: "North Macedonia", iata: "SKP" },
  { name: "Pristina International Airport", city: "Pristina", country: "Kosovo", iata: "PRN" },
  { name: "Podgorica Airport", city: "Podgorica", country: "Montenegro", iata: "TGD" },
  { name: "Sarajevo International Airport", city: "Sarajevo", country: "Bosnia and Herzegovina", iata: "SJJ" },
  { name: "Belfast International Airport", city: "Belfast", country: "United Kingdom", iata: "BFS" },
  { name: "Belfast City Airport", city: "Belfast", country: "United Kingdom", iata: "BHD" },
  { name: "Cork Airport", city: "Cork", country: "Ireland", iata: "ORK" },
  { name: "Shannon Airport", city: "Shannon", country: "Ireland", iata: "SNN" },
  { name: "Knock Airport", city: "Knock", country: "Ireland", iata: "NOC" },
  { name: "Mauritius Sir Seewoosagur Ramgoolam International Airport", city: "Plaine Magnien", country: "Mauritius", iata: "MRU" },
  { name: "Seychelles International Airport", city: "Victoria", country: "Seychelles", iata: "SEZ" },
  { name: "Antananarivo Ivato International Airport", city: "Antananarivo", country: "Madagascar", iata: "TNR" },
  { name: "Saint-Denis Roland Garros Airport", city: "Saint-Denis", country: "Réunion", iata: "RUN" },
  { name: "Dakar Blaise Diagne International Airport", city: "Dakar", country: "Senegal", iata: "DSS" },
  { name: "Abidjan Félix-Houphouët-Boigny International Airport", city: "Abidjan", country: "Ivory Coast", iata: "ABJ" },
  { name: "Accra Kotoka International Airport", city: "Accra", country: "Ghana", iata: "ACC" },
  { name: "Lagos Murtala Muhammed International Airport", city: "Lagos", country: "Nigeria", iata: "LOS" },
  { name: "Abuja Nnamdi Azikiwe International Airport", city: "Abuja", country: "Nigeria", iata: "ABV" },
  { name: "Luanda Quatro de Fevereiro Airport", city: "Luanda", country: "Angola", iata: "LAD" },
  { name: "Dar es Salaam Julius Nyerere International Airport", city: "Dar es Salaam", country: "Tanzania", iata: "DAR" },
  { name: "Entebbe International Airport", city: "Entebbe", country: "Uganda", iata: "EBB" },
  { name: "Kigali International Airport", city: "Kigali", country: "Rwanda", iata: "KGL" },
  { name: "Lusaka Kenneth Kaunda International Airport", city: "Lusaka", country: "Zambia", iata: "LUN" },
  { name: "Harare Robert Gabriel Mugabe International Airport", city: "Harare", country: "Zimbabwe", iata: "HRE" },
  { name: "Windhoek Hosea Kutako International Airport", city: "Windhoek", country: "Namibia", iata: "WDH" },
  { name: "Gaborone Sir Seretse Khama International Airport", city: "Gaborone", country: "Botswana", iata: "GBE" },
  { name: "Maputo International Airport", city: "Maputo", country: "Mozambique", iata: "MPM" },
  { name: "Saint Helena Airport", city: "Longwood", country: "Saint Helena", iata: "HLE" },
  { name: "Tunis-Carthage International Airport", city: "Tunis", country: "Tunisia", iata: "TUN" },
  { name: "Algiers Houari Boumediene Airport", city: "Algiers", country: "Algeria", iata: "ALG" },
  { name: "Tripoli International Airport", city: "Tripoli", country: "Libya", iata: "TIP" },
  { name: "Khartoum International Airport", city: "Khartoum", country: "Sudan", iata: "KRT" },
  { name: "Djibouti-Ambouli International Airport", city: "Djibouti City", country: "Djibouti", iata: "JIB" },
  { name: "Saint-Louis Airport", city: "Saint-Louis", country: "Senegal", iata: "XLS" },
  { name: "Praia Nelson Mandela International Airport", city: "Praia", country: "Cape Verde", iata: "RAI" },
  { name: "Sal Amílcar Cabral International Airport", city: "Espargos", country: "Cape Verde", iata: "SID" },
  { name: "Banjul International Airport", city: "Banjul", country: "Gambia", iata: "BJL" },
  { name: "Conakry Ahmed Sékou Touré International Airport", city: "Conakry", country: "Guinea", iata: "CKY" },
  { name: "Freetown International Airport", city: "Freetown", country: "Sierra Leone", iata: "FNA" },
  { name: "Monrovia Roberts International Airport", city: "Monrovia", country: "Liberia", iata: "ROB" },
  { name: "Ouagadougou Airport", city: "Ouagadougou", country: "Burkina Faso", iata: "OUA" },
  { name: "Niamey Diori Hamani International Airport", city: "Niamey", country: "Niger", iata: "NIM" },
  { name: "Bamako–Sénou International Airport", city: "Bamako", country: "Mali", iata: "BKO" },
  { name: "Nouakchott–Oumtounsy International Airport", city: "Nouakchott", country: "Mauritania", iata: "NKC" },
  { name: "Douala International Airport", city: "Douala", country: "Cameroon", iata: "DLA" },
  { name: "Yaoundé Nsimalen International Airport", city: "Yaoundé", country: "Cameroon", iata: "NSI" },
  { name: "Libreville Leon M'ba International Airport", city: "Libreville", country: "Gabon", iata: "LBV" },
  { name: "Port-Gentil International Airport", city: "Port-Gentil", country: "Gabon", iata: "POG" },
  { name: "Brazzaville Maya-Maya Airport", city: "Brazzaville", country: "Congo", iata: "BZV" },
  { name: "Pointe-Noire Airport", city: "Pointe-Noire", country: "Congo", iata: "PNR" },
  { name: "Kinshasa N'djili Airport", city: "Kinshasa", country: "DR Congo", iata: "FIH" },
  { name: "Lubumbashi International Airport", city: "Lubumbashi", country: "DR Congo", iata: "FBM" },
  { name: "Goma International Airport", city: "Goma", country: "DR Congo", iata: "GOM" },
  { name: "Bangui M'Poko International Airport", city: "Bangui", country: "Central African Republic", iata: "BGF" },
  { name: "N'Djamena International Airport", city: "N'Djamena", country: "Chad", iata: "NDJ" },
  { name: "Malabo International Airport", city: "Malabo", country: "Equatorial Guinea", iata: "SSG" },
  { name: "Bata Airport", city: "Bata", country: "Equatorial Guinea", iata: "BSG" },
  { name: "Sao Tome International Airport", city: "São Tomé", country: "São Tomé and Príncipe", iata: "TMS" },
  { name: "Príncipe Airport", city: "Santo António", country: "São Tomé and Príncipe", iata: "PCP" },
  { name: "Port Louis Sir Seewoosagur Ramgoolam International Airport", city: "Port Louis", country: "Mauritius", iata: "MRU" },
  { name: "Reunion Roland Garros Airport", city: "Saint-Denis", country: "Reunion", iata: "RUN" },
  { name: "Mayotte Dzaoudzi–Pamandzi International Airport", city: "Dzaoudzi", country: "Mayotte", iata: "DZA" },
  { name: "Comoros Prince Said Ibrahim International Airport", city: "Moroni", country: "Comoros", iata: "HAH" },
  { name: "Antananarivo Airport", city: "Antananarivo", country: "Madagascar", iata: "TNR" },
  { name: "Nosy Be Fascene Airport", city: "Nosy Be", country: "Madagascar", iata: "NOS" },
  { name: "Sainte Marie Airport", city: "Sainte Marie", country: "Madagascar", iata: "SMS" },
  { name: "Tulear Airport", city: "Toliara", country: "Madagascar", iata: "TLE" },
  { name: "Mahajanga Airport", city: "Mahajanga", country: "Madagascar", iata: "MJN" },
  { name: "Antsiranana Airport", city: "Antsiranana", country: "Madagascar", iata: "DIE" },
  { name: "Mananjary Airport", city: "Mananjary", country: "Madagascar", iata: "MNJ" },
  { name: "Samoa Faleolo International Airport", city: "Apia", country: "Samoa", iata: "APW" },
  { name: "Cook Islands Rarotonga International Airport", city: "Avarua", country: "Cook Islands", iata: "RAR" },
  { name: "French Polynesia Faa'a International Airport", city: "Papeete", country: "French Polynesia", iata: "PPT" },
  { name: "New Caledonia La Tontouta International Airport", city: "Nouméa", country: "New Caledonia", iata: "NOU" },
  { name: "Vanuatu Bauerfield International Airport", city: "Port Vila", country: "Vanuatu", iata: "VLI" },
  { name: "Solomon Islands Honiara International Airport", city: "Honiara", country: "Solomon Islands", iata: "HIR" },
  { name: "Kiribati Bonriki International Airport", city: "Tarawa", country: "Kiribati", iata: "TRW" },
  { name: "Tuvalu Funafuti International Airport", city: "Funafuti", country: "Tuvalu", iata: "FUN" },
  { name: "Tonga Fua'amotu International Airport", city: "Nuku'alofa", country: "Tonga", iata: "TBU" },
  { name: "Fiji Nausori International Airport", city: "Suva", country: "Fiji", iata: "SUV" },
  { name: "Papua New Guinea Jacksons International Airport", city: "Port Moresby", country: "Papua New Guinea", iata: "POM" },
  { name: "Guam Antonio B. Won Pat International Airport", city: "Hagåtña", country: "Guam", iata: "GUM" },
  { name: "Marshall Islands Amata Kabua International Airport", city: "Majuro", country: "Marshall Islands", iata: "MAJ" },
  { name: "Palau Roman Tmetuchl International Airport", city: "Airai", country: "Palau", iata: "ROR" },
  { name: "Micronesia Pohnpei International Airport", city: "Kolonia", country: "Micronesia", iata: "PNI" },
  { name: "Northern Mariana Islands Francisco C. Ada Airport", city: "Saipan", country: "Northern Mariana Islands", iata: "SPN" },
  { name: "Doncaster Sheffield Airport", city: "Doncaster", country: "United Kingdom", iata: "DSA" },
  { name: "Liverpool John Lennon Airport", city: "Liverpool", country: "United Kingdom", iata: "LPL" },
  { name: "Newcastle Airport", city: "Newcastle", country: "United Kingdom", iata: "NCL" },
  { name: "East Midlands Airport", city: "Derby", country: "United Kingdom", iata: "EMA" },
  { name: "Southampton Airport", city: "Southampton", country: "United Kingdom", iata: "SOU" },
  { name: "Bordeaux-Mérignac Airport", city: "Bordeaux", country: "France", iata: "BOD" },
  { name: "Nantes Atlantique Airport", city: "Nantes", country: "France", iata: "NTE" },
  { name: "Strasbourg Airport", city: "Strasbourg", country: "France", iata: "SXB" },
  { name: "Montpellier–Méditerranée Airport", city: "Montpellier", country: "France", iata: "MPL" },
  { name: "Valencia Airport", city: "Valencia", country: "Spain", iata: "VLC" },
  { name: "Seville Airport", city: "Seville", country: "Spain", iata: "SVQ" },
  { name: "Bilbao Airport", city: "Bilbao", country: "Spain", iata: "BIO" },
  { name: "Alicante–Elche Miguel Hernández Airport", city: "Alicante", country: "Spain", iata: "ALC" },
  { name: "Málaga–Costa del Sol Airport", city: "Málaga", country: "Spain", iata: "AGP" },
  { name: "Palma de Mallorca Airport", city: "Palma de Mallorca", country: "Spain", iata: "PMI" },
  { name: "Tenerife South Airport", city: "Tenerife", country: "Spain", iata: "TFS" },
  { name: "Gran Canaria Airport", city: "Las Palmas", country: "Spain", iata: "LPA" },
  { name: "Lanzarote Airport", city: "Arrecife", country: "Spain", iata: "ACE" },
  { name: "Fuerteventura Airport", city: "Puerto del Rosario", country: "Spain", iata: "FUE" },
  { name: "Ibiza Airport", city: "Ibiza", country: "Spain", iata: "IBZ" },
  { name: "Porto Airport", city: "Porto", country: "Portugal", iata: "OPO" },
  { name: "Faro Airport", city: "Faro", country: "Portugal", iata: "FAO" },
  { name: "Madeira Airport", city: "Funchal", country: "Portugal", iata: "FNC" },
  { name: "Ponta Delgada Airport", city: "Ponta Delgada", country: "Portugal", iata: "PDL" },
  { name: "Lyon Airport", city: "Lyon", country: "France", iata: "LYS" },
  { name: "Bologna Airport", city: "Bologna", country: "Italy", iata: "BLQ" },
  { name: "Bari Karol Wojtyła Airport", city: "Bari", country: "Italy", iata: "BRI" },
  { name: "Brindisi Airport", city: "Brindisi", country: "Italy", iata: "BDS" },
  { name: "Cagliari Elmas Airport", city: "Cagliari", country: "Italy", iata: "CAG" },
  { name: "Olbia Costa Smeralda Airport", city: "Olbia", country: "Italy", iata: "OLB" },
  { name: "Alghero-Fertilia Airport", city: "Alghero", country: "Italy", iata: "AHO" },
  { name: "Lamezia Terme International Airport", city: "Lamezia Terme", country: "Italy", iata: "SUF" },
  { name: "Reggio Calabria Airport", city: "Reggio Calabria", country: "Italy", iata: "REG" },
  { name: "Nimes Alès Camargue Cévennes Airport", city: "Nîmes", country: "France", iata: "FNI" },
  { name: "Brest Bretagne Airport", city: "Brest", country: "France", iata: "BES" },
  { name: "Toulon–Hyères Airport", city: "Toulon", country: "France", iata: "TLN" },
  { name: "Clermont-Ferrand Auvergne Airport", city: "Clermont-Ferrand", country: "France", iata: "CFE" },
  { name: "Perpignan–Rivesaltes Airport", city: "Perpignan", country: "France", iata: "PGF" },
  { name: "Biarritz Pays Basque Airport", city: "Biarritz", country: "France", iata: "BIQ" },
  { name: "Pau Pyrénées Airport", city: "Pau", country: "France", iata: "PUF" },
  { name: "Rennes–Saint-Jacques Airport", city: "Rennes", country: "France", iata: "RNS" },
  { name: "Limoges – Bellegarde Airport", city: "Limoges", country: "France", iata: "LIG" },
  { name: "Poitiers–Biard Airport", city: "Poitiers", country: "France", iata: "PIS" },
  { name: "Bergerac Dordogne Périgord Airport", city: "Bergerac", country: "France", iata: "EGC" },
  { name: "Rodez–Aveyron Airport", city: "Rodez", country: "France", iata: "RDZ" },
  { name: "Carcassonne Airport", city: "Carcassonne", country: "France", iata: "CCF" },
  { name: "Tarbes–Lourdes–Pyrénées Airport", city: "Tarbes", country: "France", iata: "LDE" },
  { name: "Luxor International Airport", city: "Luxor", country: "Egypt", iata: "LXR" },
  { name: "Hurghada International Airport", city: "Hurghada", country: "Egypt", iata: "HRG" },
  { name: "Sharm El Sheikh International Airport", city: "Sharm El Sheikh", country: "Egypt", iata: "SSH" },
  { name: "Alexandria Borg El Arab Airport", city: "Alexandria", country: "Egypt", iata: "HBE" },
  { name: "Aswan International Airport", city: "Aswan", country: "Egypt", iata: "ASW" },
  { name: "Marsa Alam International Airport", city: "Marsa Alam", country: "Egypt", iata: "RMF" },
  { name: "Sohag International Airport", city: "Sohag", country: "Egypt", iata: "HMB" },
  { name: "Assiut Airport", city: "Assiut", country: "Egypt", iata: "ATZ" },
  { name: "Al Abraq International Airport", city: "Bayda", country: "Libya", iata: "LAQ" },
  { name: "Benina International Airport", city: "Benghazi", country: "Libya", iata: "BEN" },
  { name: "Misrata Airport", city: "Misrata", country: "Libya", iata: "MRA" },
  { name: "Sebha Airport", city: "Sebha", country: "Libya", iata: "SEB" },
  { name: "Tobruk Airport", city: "Tobruk", country: "Libya", iata: "TOB" },
  { name: "Labraq Airport", city: "Bayda", country: "Libya", iata: "LAQ" },
  { name: "Ghadames Airport", city: "Ghadames", country: "Libya", iata: "GHT" },
  { name: "Ghat Airport", city: "Ghat", country: "Libya", iata: "GHT" },
  { name: "Ubari Airport", city: "Ubari", country: "Libya", iata: "QUB" },
  { name: "Kufra Airport", city: "Kufra", country: "Libya", iata: "AKF" },
  { name: "Agadir–Al Massira Airport", city: "Agadir", country: "Morocco", iata: "AGA" },
  { name: "Marrakesh Menara Airport", city: "Marrakesh", country: "Morocco", iata: "RAK" },
  { name: "Fes–Saïss Airport", city: "Fes", country: "Morocco", iata: "FEZ" },
  { name: "Tangier Ibn Battouta Airport", city: "Tangier", country: "Morocco", iata: "TNG" },
  { name: "Rabat–Salé Airport", city: "Rabat", country: "Morocco", iata: "RBA" },
  { name: "Nador Airport", city: "Nador", country: "Morocco", iata: "NDR" },
  { name: "Oujda Angads Airport", city: "Oujda", country: "Morocco", iata: "OUD" },
  { name: "Laayoune Hassan I Airport", city: "Laayoune", country: "Western Sahara", iata: "EUN" },
  { name: "Dakhla Airport", city: "Dakhla", country: "Western Sahara", iata: "VIL" },
  { name: "Monastir Habib Bourguiba International Airport", city: "Monastir", country: "Tunisia", iata: "MIR" },
  { name: "Djerba–Zarzis International Airport", city: "Djerba", country: "Tunisia", iata: "DJE" },
  { name: "Enfidha–Hammamet International Airport", city: "Enfidha", country: "Tunisia", iata: "NBE" },
  { name: "Sfax–Thyna International Airport", city: "Sfax", country: "Tunisia", iata: "SFA" },
  { name: "Tozeur–Nefta International Airport", city: "Tozeur", country: "Tunisia", iata: "TOE" },
  { name: "Tabarka–Aïn Draham International Airport", city: "Tabarka", country: "Tunisia", iata: "TBJ" },
  { name: "Gafsa–Ksar International Airport", city: "Gafsa", country: "Tunisia", iata: "GAF" },
  { name: "Gabès–Matmata International Airport", city: "Tunis", country: "Tunisia", iata: "GAE" },
  { name: "Durban King Shaka International Airport", city: "Durban", country: "South Africa", iata: "DUR" },
  { name: "Port Elizabeth International Airport", city: "Port Elizabeth", country: "South Africa", iata: "PLZ" },
  { name: "East London Airport", city: "East London", country: "South Africa", iata: "ELS" },
  { name: "George Airport", city: "George", country: "South Africa", iata: "GRJ" },
  { name: "Bloemfontein Airport", city: "Bloemfontein", country: "South Africa", iata: "BFN" },
  { name: "Kimberley Airport", city: "Kimberley", country: "South Africa", iata: "KIM" },
  { name: "Upington Airport", city: "Upington", country: "South Africa", iata: "UTN" },
  { name: "Polokwane International Airport", city: "Polokwane", country: "South Africa", iata: "PTG" },
  { name: "Nelspruit Kruger Mpumalanga International Airport", city: "Nelspruit", country: "South Africa", iata: "MQP" },
  { name: "Lanseria International Airport", city: "Johannesburg", country: "South Africa", iata: "HLA" },
  { name: "Richards Bay Airport", city: "Richards Bay", country: "South Africa", iata: "RCB" },
  { name: "Skukuza Airport", city: "Skukuza", country: "South Africa", iata: "SZK" },
  { name: "Maseru Moshoeshoe I International Airport", city: "Maseru", country: "Lesotho", iata: "MSU" },
  { name: "Manzini King Mswati III International Airport", city: "Manzini", country: "Eswatini", iata: "SHO" },
  { name: "Matsapha Airport", city: "Manzini", country: "Eswatini", iata: "MTS" },
  { name: "Beira International Airport", city: "Beira", country: "Mozambique", iata: "BEW" },
  { name: "Nampula Airport", city: "Nampula", country: "Mozambique", iata: "APL" },
  { name: "Pemba Airport", city: "Pemba", country: "Mozambique", iata: "POL" },
  { name: "Vilankulo Airport", city: "Vilankulo", country: "Mozambique", iata: "VNX" },
  { name: "Tete Airport", city: "Tete", country: "Mozambique", iata: "TET" },
  { name: "Lichinga Airport", city: "Lichinga", country: "Mozambique", iata: "VXC" },
  { name: "Inhambane Airport", city: "Inhambane", country: "Mozambique", iata: "INH" },
  { name: "Victoria Falls Airport", city: "Victoria Falls", country: "Zimbabwe", iata: "VFA" },
  { name: "Bulawayo Joshua Mqabuko Nkomo International Airport", city: "Bulawayo", country: "Zimbabwe", iata: "BUQ" },
  { name: "Livinstone Harry Mwanga Nkumbula International Airport", city: "Livingstone", country: "Zambia", iata: "LVI" },
  { name: "Ndola Simon Mwansa Kapwepwe International Airport", city: "Ndola", country: "Zambia", iata: "NLA" },
  { name: "Mfuwe Airport", city: "Mfuwe", country: "Zambia", iata: "MFU" },
  { name: "Solwezi Airport", city: "Solwezi", country: "Zambia", iata: "SLI" },
  { name: "Kasama Airport", city: "Kasama", country: "Zambia", iata: "KSA" },
  { name: "Mansha Airport", city: "Mansa", country: "Zambia", iata: "MNS" },
  { name: "Lilongwe Kamuzu International Airport", city: "Lilongwe", country: "Malawi", iata: "LLW" },
  { name: "Blantyre Chileka International Airport", city: "Blantyre", country: "Malawi", iata: "BLZ" },
  { name: "Zanzibar Abeid Amani Karume International Airport", city: "Zanzibar", country: "Tanzania", iata: "ZNZ" },
  { name: "Kilimanjaro International Airport", city: "Arusha", country: "Tanzania", iata: "JRO" },
  { name: "Mwanza Airport", city: "Mwanza", country: "Tanzania", iata: "MWZ" },
  { name: "Arusha Airport", city: "Arusha", country: "Tanzania", iata: "ARK" },
  { name: "Dodoma Airport", city: "Dodoma", country: "Tanzania", iata: "DOD" },
  { name: "Mbeya Airport", city: "Mbeya", country: "Tanzania", iata: "MBI" },
  { name: "Mombasa Moi International Airport", city: "Mombasa", country: "Kenya", iata: "MBA" },
  { name: "Kisumu International Airport", city: "Kisumu", country: "Kenya", iata: "KIS" },
  { name: "Eldoret International Airport", city: "Eldoret", country: "Kenya", iata: "EDL" },
  { name: "Malindi Airport", city: "Malindi", country: "Kenya", iata: "MYD" },
  { name: "Lamu Manda Airport", city: "Lamu", country: "Kenya", iata: "LAU" },
  { name: "Ukunda Airport", city: "Diani Beach", country: "Kenya", iata: "UKA" },
  { name: "Lodwar Airport", city: "Lodwar", country: "Kenya", iata: "LOK" },
  { name: "Bujumbura International Airport", city: "Bujumbura", country: "Burundi", iata: "BJM" },
  { name: "Gitega Airport", city: "Gitega", country: "Burundi", iata: "GID" },
  { name: "Port Harcourt International Airport", city: "Port Harcourt", country: "Nigeria", iata: "PHC" },
  { name: "Kano Mallam Aminu Kano International Airport", city: "Kano", country: "Nigeria", iata: "KAN" },
  { name: "Enugu Akanu Ibiam International Airport", city: "Enugu", country: "Nigeria", iata: "ENU" },
  { name: "Owerri Sam Mbakwe Airport", city: "Owerri", country: "Nigeria", iata: "QOW" },
  { name: "Benin City Airport", city: "Benin City", country: "Nigeria", iata: "BNI" },
  { name: "Asaba International Airport", city: "Asaba", country: "Nigeria", iata: "ABB" },
  { name: "Calabar Margaret Ekpo International Airport", city: "Calabar", country: "Nigeria", iata: "CBQ" },
  { name: "Jos Yakubu Gowon Airport", city: "Jos", country: "Nigeria", iata: "JOS" },
  { name: "Maiduguri International Airport", city: "Maiduguri", country: "Nigeria", iata: "MIU" },
  { name: "Sokoto Sadiq Abubakar III International Airport", city: "Sokoto", country: "Nigeria", iata: "SKO" },
  { name: "Uyo Akwa Ibom Airport", city: "Uyo", country: "Nigeria", iata: "QUO" },
  { name: "Warri Airport", city: "Warri", country: "Nigeria", iata: "QRW" },
  { name: "Yola Airport", city: "Yola", country: "Nigeria", iata: "YOL" },
  { name: "Kastina Airport", city: "Katsina", country: "Nigeria", iata: "DKA" },
  { name: "Ibadan Airport", city: "Ibadan", country: "Nigeria", iata: "IBA" },
  { name: "Ilorin International Airport", city: "Ilorin", country: "Nigeria", iata: "ILR" },
  { name: "Akure Airport", city: "Akure", country: "Nigeria", iata: "AKR" },
  { name: "Cotonou Cadjehoun Airport", city: "Cotonou", country: "Benin", iata: "COO" },
  { name: "Lomé–Tokoin International Airport", city: "Lomé", country: "Togo", iata: "LFW" },
  { name: "Bata International Airport", city: "Bata", country: "Equatorial Guinea", iata: "BSG" },
  { name: "Owendo Airport", city: "Libreville", country: "Gabon", iata: "OWE" },
  { name: "Franceville M'Vengue Airport", city: "Franceville", country: "Gabon", iata: "MVB" },
  { name: "Moanda Airport", city: "Moanda", country: "Gabon", iata: "MFF" },
  { name: "Tchibanga Airport", city: "Tchibanga", country: "Gabon", iata: "TCH" },
  { name: "Lambarene Airport", city: "Lambarene", country: "Gabon", iata: "LBQ" },
  { name: "Mouila Airport", city: "Mouila", country: "Gabon", iata: "MJL" },
  { name: "Makokou Airport", city: "Makokou", country: "Gabon", iata: "MKU" },
  { name: "Koulamoutou Airport", city: "Koulamoutou", country: "Gabon", iata: "KOU" },
  { name: "Oyem Airport", city: "Oyem", country: "Gabon", iata: "OYE" },
  { name: "Bitam Airport", city: "Bitam", country: "Gabon", iata: "BMM" },
  { name: "Omboue Airport", city: "Omboue", country: "Gabon", iata: "OMB" },
  { name: "Gamboma Airport", city: "Gamboma", country: "Congo", iata: "GMM" },
  { name: "Impfondo Airport", city: "Impfondo", country: "Congo", iata: "ION" },
  { name: "Ouesso Airport", city: "Ouesso", country: "Congo", iata: "OUE" },
  { name: "Owando Airport", city: "Owando", country: "Congo", iata: "FTX" },
  { name: "Djambala Airport", city: "Djambala", country: "Congo", iata: "DJM" },
  { name: "Ewo Airport", city: "Ewo", country: "Congo", iata: "EWO" },
  { name: "Makoua Airport", city: "Makoua", country: "Congo", iata: "MKJ" },
  { name: "Mossendjo Airport", city: "Mossendjo", country: "Congo", iata: "MSX" },
  { name: "Dolisie Airport", city: "Dolisie", country: "Congo", iata: "DIS" },
  { name: "Sibiti Airport", city: "Sibiti", country: "Congo", iata: "SIB" },
  { name: "Yokangassi Airport", city: "Nkayi", country: "Congo", iata: "NKY" },
  { name: "Zanaga Airport", city: "Zanaga", country: "Congo", iata: "ANL" },
  { name: "Kindu Airport", city: "Kindu", country: "DR Congo", iata: "KND" },
  { name: "Kisangani Bangoka International Airport", city: "Kisangani", country: "DR Congo", iata: "FKI" },
  { name: "Kananga Airport", city: "Kananga", country: "DR Congo", iata: "KGA" },
  { name: "Mbuji-Mayi Airport", city: "Mbuji-Mayi", country: "DR Congo", iata: "MJM" },
  { name: "Mbandaka Airport", city: "Mbandaka", country: "DR Congo", iata: "MDK" },
  { name: "Bukavu Kavumu Airport", city: "Bukavu", country: "DR Congo", iata: "BKY" },
  { name: "Kalemie Airport", city: "Kalemie", country: "DR Congo", iata: "FMI" },
  { name: "Gemena Airport", city: "Gemena", country: "DR Congo", iata: "GMA" },
  { name: "Isiro Matari Airport", city: "Isiro", country: "DR Congo", iata: "IRP" },
  { name: "Bunia Airport", city: "Bunia", country: "DR Congo", iata: "BUX" },
  { name: "Tshikapa Airport", city: "Tshikapa", country: "DR Congo", iata: "TSH" },
  { name: "Kolwezi Airport", city: "Kolwezi", country: "DR Congo", iata: "KWZ" },
  { name: "Kikwit Airport", city: "Kikwit", country: "DR Congo", iata: "KKW" },
  { name: "Bandundu Airport", city: "Bandundu", country: "DR Congo", iata: "FDU" },
  { name: "Boende Airport", city: "Boende", country: "DR Congo", iata: "BNB" },
  { name: "Basankusu Airport", city: "Basankusu", country: "DR Congo", iata: "BSU" },
  { name: "Inongo Airport", city: "Inongo", country: "DR Congo", iata: "INO" },
  { name: "Kole Airport", city: "Kole", country: "DR Congo", iata: "KOL" },
  { name: "Lodja Airport", city: "Lodja", country: "DR Congo", iata: "LJA" },
  { name: "Lusambo Airport", city: "Lusambo", country: "DR Congo", iata: "LBO" },
  { name: "Muanda Airport", city: "Muanda", country: "DR Congo", iata: "MND" },
  { name: "Nioki Airport", city: "Nioki", country: "DR Congo", iata: "NIO" },
  { name: "Basongo Airport", city: "Basongo", country: "DR Congo", iata: "BAN" },
  { name: "Dekese Airport", city: "Dekese", country: "DR Congo", iata: "DKS" },
  { name: "Ilebo Airport", city: "Ilebo", country: "DR Congo", iata: "ILL" },
  { name: "Lisala Airport", city: "Lisala", country: "DR Congo", iata: "LIQ" },
  { name: "Bumba Airport", city: "Bumba", country: "DR Congo", iata: "BMB" },
  { name: "Aketi Airport", city: "Aketi", country: "DR Congo", iata: "AEK" },
  { name: "Buta Airport", city: "Buta", country: "DR Congo", iata: "BZU" },
  { name: "Ango Airport", city: "Ango", country: "DR Congo", iata: "ANG" },
  { name: "Dungu Airport", city: "Dungu", country: "DR Congo", iata: "DNG" },
  { name: "Faradje Airport", city: "Faradje", country: "DR Congo", iata: "FAD" },
  { name: "Watsa Airport", city: "Watsa", country: "DR Congo", iata: "WTS" },
  { name: "Aru Airport", city: "Aru", country: "DR Congo", iata: "ARU" },
  { name: "Mahagi Airport", city: "Mahagi", country: "DR Congo", iata: "MAH" },
  { name: "Manono Airport", city: "Manono", country: "DR Congo", iata: "MNO" },
  { name: "Kongolo Airport", city: "Kongolo", country: "DR Congo", iata: "KOO" },
  { name: "Kabalo Airport", city: "Kabalo", country: "DR Congo", iata: "KBO" },
  { name: "Nyunzu Airport", city: "Nyunzu", country: "DR Congo", iata: "NYN" },
  { name: "Pweto Airport", city: "Pweto", country: "DR Congo", iata: "PWO" },
  { name: "Mitwaba Airport", city: "Mitwaba", country: "DR Congo", iata: "MTW" },
  { name: "Kamina Airport", city: "Kamina", country: "DR Congo", iata: "KMN" },
  { name: "Sandoa Airport", city: "Sandoa", country: "DR Congo", iata: "SND" },
  { name: "Kasaji Airport", city: "Kasaji", country: "DR Congo", iata: "KSI" },
  { name: "Dilolo Airport", city: "Dilolo", country: "DR Congo", iata: "DLO" },
  { name: "Kilwa Airport", city: "Kilwa", country: "DR Congo", iata: "KIL" },
  { name: "Moba Airport", city: "Moba", country: "DR Congo", iata: "BDV" },
  { name: "Kapanga Airport", city: "Kapanga", country: "DR Congo", iata: "KAP" },
  { name: "Kaniama Airport", city: "Kaniama", country: "DR Congo", iata: "KNA" }
];
