export interface Port {
  name: string;
  city: string;
  country: string;
  code: string; // UN/LOCODE or Port Code
}

export const SEA_PORTS: Port[] = [
  { name: "Port of Singapore", city: "Singapore", country: "Singapore", code: "SGSIN" },
  { name: "Port of Shanghai", city: "Shanghai", country: "China", code: "CNSHA" },
  { name: "Port of Ningbo-Zhoushan", city: "Ningbo", country: "China", code: "CNNGB" },
  { name: "Port of Shenzhen", city: "Shenzhen", country: "China", code: "CNSZX" },
  { name: "Port of Guangzhou", city: "Guangzhou", country: "China", code: "CNCAN" },
  { name: "Port of Busan", city: "Busan", country: "South Korea", code: "KRPUS" },
  { name: "Port of Qingdao", city: "Qingdao", country: "China", code: "CNTAO" },
  { name: "Port of Hong Kong", city: "Hong Kong", country: "Hong Kong", code: "HKHKG" },
  { name: "Port of Tianjin", city: "Tianjin", country: "China", code: "TSN" },
  { name: "Port of Rotterdam", city: "Rotterdam", country: "Netherlands", code: "NLRTM" },
  { name: "Port of Jebel Ali", city: "Dubai", country: "United Arab Emirates", code: "AEJEA" },
  { name: "Port of Klang", city: "Klang", country: "Malaysia", code: "MYPKG" },
  { name: "Port of Antwerp-Bruges", city: "Antwerp", country: "Belgium", code: "BEANT" },
  { name: "Port of Xiamen", city: "Xiamen", country: "China", code: "CNXMN" },
  { name: "Port of Kaohsiung", city: "Kaohsiung", country: "Taiwan", code: "TWKHH" },
  { name: "Port of Los Angeles", city: "Los Angeles", country: "United States", code: "USLAX" },
  { name: "Port of Long Beach", city: "Long Beach", country: "United States", code: "USLGB" },
  { name: "Port of Hamburg", city: "Hamburg", country: "Germany", code: "DEHAM" },
  { name: "Port of Tanjung Pelepas", city: "Johor", country: "Malaysia", code: "MYTPP" },
  { name: "Port of Laem Chabang", city: "Chonburi", country: "Thailand", code: "THLCH" },
  { name: "Port of Colombo", city: "Colombo", country: "Sri Lanka", code: "LKCMB" },
  { name: "Port of Mundra", city: "Mundra", country: "India", code: "INMUN" },
  { name: "Port of Nhava Sheva (JNPT)", city: "Navi Mumbai", country: "India", code: "INNSA" },
  { name: "Port of Ho Chi Minh City", city: "Ho Chi Minh City", country: "Vietnam", code: "VNSGN" },
  { name: "Port of Valencia", city: "Valencia", country: "Spain", code: "ESVLC" },
  { name: "Port of Piraeus", city: "Piraeus", country: "Greece", code: "GRPIR" },
  { name: "Port of Algeciras", city: "Algeciras", country: "Spain", code: "ESALG" },
  { name: "Port of Bremerhaven", city: "Bremerhaven", country: "Germany", code: "DEBRV" },
  { name: "Port of Savannah", city: "Savannah", country: "United States", code: "USSAV" },
  { name: "Port of Felixstowe", city: "Felixstowe", country: "United Kingdom", code: "GBFXT" },
  { name: "Port of Santos", city: "Santos", country: "Brazil", code: "BRSSZ" },
  { name: "Port of Jeddah", city: "Jeddah", country: "Saudi Arabia", code: "SAJED" },
  { name: "Port of Salalah", city: "Salalah", country: "Oman", code: "OMSLL" },
  { name: "Port of Mundra", city: "Kutch", country: "India", code: "INMUN" },
  { name: "Port of Vishakhapatnam", city: "Vishakhapatnam", country: "India", code: "INVTZ" },
  { name: "Port of Chennai", city: "Chennai", country: "India", code: "INMAA" },
  { name: "Port of Kolkata", city: "Kolkata", country: "India", code: "INCCU" },
  { name: "Port of Pipavav", city: "Pipavav", country: "India", code: "INPAV" },
  { name: "Port of Krishnapatnam", city: "Nellore", country: "India", code: "INKPI" },
  { name: "Port of Ennore", city: "Chennai", country: "India", code: "INENR" },
  { name: "Port of Tuticorin", city: "Tuticorin", country: "India", code: "INTUT" },
  { name: "Port of Kandla", city: "Kandla", country: "India", code: "INKAN" },
  { name: "Port of Mormugao", city: "Goa", country: "India", code: "INMRM" },
  { name: "Port of Paradip", city: "Paradip", country: "India", code: "INPPR" },
  { name: "Port of Mumbai", city: "Mumbai", country: "India", code: "INBOM" },
  { name: "Port of Haifa", city: "Haifa", country: "Israel", code: "ILHFA" },
  { name: "Port of Ashdod", city: "Ashdod", country: "Israel", code: "ILASH" },
  { name: "Port of Aqaba", city: "Aqaba", country: "Jordan", code: "JOAQB" },
  { name: "Port of Damietta", city: "Damietta", country: "Egypt", code: "EGDAM" },
  { name: "Port of Alexandria", city: "Alexandria", country: "Egypt", code: "EGALY" },
  { name: "Suez Canal Container Terminal", city: "Port Said", country: "Egypt", code: "EGPSD" },
  { name: "Port of Casablanca", city: "Casablanca", country: "Morocco", code: "MACOA" },
  { name: "Port of Tangier Med", city: "Tangier", country: "Morocco", code: "MATNG" },
  { name: "Port of Durban", city: "Durban", country: "South Africa", code: "ZADUR" },
  { name: "Port of Cape Town", city: "Cape Town", country: "South Africa", code: "ZACPT" },
  { name: "Port of Port Elizabeth", city: "Port Elizabeth", country: "South Africa", code: "ZAPEZ" },
  { name: "Port of Richards Bay", city: "Richards Bay", country: "South Africa", code: "ZARCB" },
  { name: "Port of Ngqura", city: "Port Elizabeth", country: "South Africa", code: "ZANQG" },
  { name: "Port of Maputo", city: "Maputo", country: "Mozambique", code: "MZMPM" },
  { name: "Port of Beira", city: "Beira", country: "Mozambique", code: "MZBEW" },
  { name: "Port of Nacala", city: "Nacala", country: "Mozambique", code: "MZNAC" },
  { name: "Port of Dar es Salaam", city: "Dar es Salaam", country: "Tanzania", code: "TZDAR" },
  { name: "Port of Mombasa", city: "Mombasa", country: "Kenya", code: "KEMBA" },
  { name: "Port of Djibouti", city: "Djibouti", country: "Djibouti", code: "DJJIB" },
  { name: "Port of Aden", city: "Aden", country: "Yemen", code: "YEADE" },
  { name: "Port of Karachi", city: "Karachi", country: "Pakistan", code: "PKKHI" },
  { name: "Port Qasim", city: "Karachi", country: "Pakistan", code: "PKBQP" },
  { name: "Port of Chittagong", city: "Chittagong", country: "Bangladesh", code: "BDCGP" },
  { name: "Port of Yangon", city: "Yangon", country: "Myanmar", code: "MMRGN" },
  { name: "Port of Bangkok", city: "Bangkok", country: "Thailand", code: "THBKK" },
  { name: "Port of Surabaya", city: "Surabaya", country: "Indonesia", code: "IDSUB" },
  { name: "Port of Belawan", city: "Medan", country: "Indonesia", code: "IDBLW" },
  { name: "Port of Semarang", city: "Semarang", country: "Indonesia", code: "IDSRG" },
  { name: "Port of Manila", city: "Manila", country: "Philippines", code: "PHMNL" },
  { name: "Port of Cebu", city: "Cebu", country: "Philippines", code: "PHCEB" },
  { name: "Port of Tokyo", city: "Tokyo", country: "Japan", code: "JPTOK" },
  { name: "Port of Yokohama", city: "Yokohama", country: "Japan", code: "JPYOK" },
  { name: "Port of Nagoya", city: "Nagoya", country: "Japan", code: "JPNGO" },
  { name: "Port of Osaka", city: "Osaka", country: "Japan", code: "JPOSA" },
  { name: "Port of Kobe", city: "Kobe", country: "Japan", code: "JPUKB" },
  { name: "Port of Brisbane", city: "Brisbane", country: "Australia", code: "AUBNE" },
  { name: "Port of Sydney (Botany)", city: "Sydney", country: "Australia", code: "AUSYD" },
  { name: "Port of Melbourne", city: "Melbourne", country: "Australia", code: "AUMEL" },
  { name: "Port of Adelaide", city: "Adelaide", country: "Australia", code: "AUADL" },
  { name: "Port of Perth (Fremantle)", city: "Perth", country: "Australia", code: "AUFRE" },
  { name: "Port of Auckland", city: "Auckland", country: "New Zealand", code: "NZAKL" },
  { name: "Port of Tauranga", city: "Tauranga", country: "New Zealand", code: "NZTRG" },
  { name: "Port of Lyttelton", city: "Christchurch", country: "New Zealand", code: "NZLYT" },
  { name: "Port of Vancouver", city: "Vancouver", country: "Canada", code: "CAVAN" },
  { name: "Port of Prince Rupert", city: "Prince Rupert", country: "Canada", code: "CAPRR" },
  { name: "Port of Montreal", city: "Montreal", country: "Canada", code: "CAMTR" },
  { name: "Port of Halifax", city: "Halifax", country: "Canada", code: "CAHAL" },
  { name: "Port of New York & New Jersey", city: "New York", country: "United States", code: "USNYC" },
  { name: "Port of Houston", city: "Houston", country: "United States", code: "USHOU" },
  { name: "Port of Seattle", city: "Seattle", country: "United States", code: "USSEA" },
  { name: "Port of Tacoma", city: "Tacoma", country: "United States", code: "USTAC" },
  { name: "Port of Oakland", city: "Oakland", country: "United States", code: "USOAK" },
  { name: "Port of Miami", city: "Miami", country: "United States", code: "USMIA" },
  { name: "Port of Port Everglades", city: "Fort Lauderdale", country: "United States", code: "USPEF" },
  { name: "Port of Jacksonville", city: "Jacksonville", country: "United States", code: "USJAX" },
  { name: "Port of Charleston", city: "Charl Charleston", country: "United States", code: "USCHS" },
  { name: "Port of Norfolk (Virginia)", city: "Norfolk", country: "United States", code: "USORF" },
  { name: "Port of Veracruz", city: "Veracruz", country: "Mexico", code: "MXVER" },
  { name: "Port of Manzanillo", city: "Manzanillo", country: "Mexico", code: "MXZLO" },
  { name: "Port of Lazaro Cardenas", city: "Lazaro Cardenas", country: "Mexico", code: "MXLCD" },
  { name: "Port of Colon (MIT/Cristobal/Evergreen)", city: "Colon", country: "Panama", code: "PAONX" },
  { name: "Port of Balboa", city: "Balboa", country: "Panama", code: "PABLB" },
  { name: "Port of Cartagena", city: "Cartagena", country: "Colombia", code: "COCTG" },
  { name: "Port of Buenaventura", city: "Buenaventura", country: "Colombia", code: "COBUN" },
  { name: "Port of Guayaquil", city: "Guayaquil", country: "Ecuador", code: "GYE" },
  { name: "Port of Callao", city: "Callao", country: "Peru", code: "PELIM" },
  { name: "Port of San Antonio", city: "San Antonio", country: "Chile", code: "CLSAI" },
  { name: "Port of Valparaiso", city: "Valparaiso", country: "Chile", code: "CLVAP" },
  { name: "Port of Itajai", city: "Itajai", country: "Brazil", code: "BRITJ" },
  { name: "Port of Paranagua", city: "Paranagua", country: "Brazil", code: "BRPNG" },
  { name: "Port of Rio Grande", city: "Rio Grande", country: "Brazil", code: "BRRIG" },
  { name: "Port of Montevideo", city: "Montevideo", country: "Uruguay", code: "UYMVD" },
  { name: "Port of Buenos Aires", city: "Buenos Aires", country: "Argentina", code: "BUE" },
];
